### PR TITLE
fix: conditional includes are not working properly on Windows

### PR DESCRIPTION
**Pull request by StyleShit**
I was actually trying to work on an issue and noticed that

### CODE REVIEW

**Comment by StyleShit** [comment]
@timvandijck

**Comment by freekmurze** [comment]
The tests seem to be failing, could you take a look at that?

**Comment by StyleShit** [comment]
@freekmurze 

Seems like those are the livewire tests that for some reason didn't fail on the previous PR.
I've fixed it in this PR. Do you want a separate one for that?

___
BTW, the reason is that some of the workflows installed livewire 2.x (probably due to the PHP/Laravel version), which means I had to take both cases into account (2.x, 3.x) when cleaning livewire's output.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
